version: 2.1

orbs:
  node: circleci/node@2.1.0
  
jobs:
  klient:
    executor: node/default
    steps:
      - checkout
      - run: 
          command: npm install
          working_directory: ./client
      - run: 
          command: npm test
          working_directory: ./client
  serwer:
    executor: node/default 
    steps:
      - checkout
      - run:
          command: npm install
          working_directory: ./server
      - run: 
          command: npm test
          working_directory: ./server
  publikacja:
    machine: true
    steps:
      - checkout
      - run: |
          echo "$DOCKER_PASS" | docker login -u $DOCKER_USER --password-stdin
          docker build ./server -t mkapust8/node-svr:latest
          docker push mkapust8/node-svr:latest
      - run: |
          echo "$DOCKER_PASS" | docker login -u $DOCKER_USER --password-stdin
          docker build ./client -t mkapust8/react-client:latest
          docker push mkapust8/react-client:latest


workflows:
  test:
    jobs:
      - serwer
      - klient
      - publikacja