version: 2.1
orbs:
  docker: circleci/docker@1.2.1
  
jobs:
  
  klient:
    executor:
      name: docker/docker
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run: 
        command: node/install
        working_directory: ./client
      - run: 
        command: npm test
        working_directory: ./client
  serwer:
    executor:
      name: docker/docker
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
        command: node/install
        working_directory: ./server
      - run: 
        command: npm test
        working_directory: ./server


workflows:
  versions: 2
  test:
    jobs:
      - klient
      - serwer