version: 2.1

executors:
  node:
    docker:
    - image: circleci/node:10
  
jobs:
  klient:
    executor: node
    steps:
      - checkout
      - run: 
          command: npm install
          working_directory: ./client
      - run: 
          command: npm test
          working_directory: ./client
  serwer:
    executor: node
    steps:
      - checkout
      - run:
          command: npm install
          working_directory: ./server
      - run: 
          command: npm test
          working_directory: ./server


workflows:
  version: 2
  test:
    jobs:
      - serwer:
        filters:
          branches:
            only: master
      - klient:
        filters:
          branches:
            only: master