version: 2.1
orbs:
  docker: circleci/docker@1.2.1
  node: circleci/node@2.1.0
jobs:
  
  klient:
    executor:
      name: docker/docker
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run: 
        working_directory: client
      - node/install
      - npm test
  serwer:
    executor:
      name: docker/docker
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
        working_directory: server
      - node/install
      - npm test


workflows:
    test:
      jobs:
        - klient
        - serwer