version: 2.1

orbs:
  node: circleci/node@2.1.0
  
jobs:
  klient:
    executor: node/default
    steps:
      - checkout
      - run: 
          command: npm install
          working_directory: ./client
      - run: 
          command: npm test
          working_directory: ./client
  serwer:
    executor: node/default
    steps:
      - checkout
      - run:
          command: npm install
          working_directory: ./server
      - run: 
          command: npm test
          working_directory: ./server


workflows:
  test:
    jobs:
      - serwer
      - klient