version: 2.1
orbs:
  node: circleci/node@2.1.0
jobs:
  klient:
    executor:
      name: node/default
    steps:
      - checkout
      - run: 
        working_directory: client
        npm install
        npm test
  serwer:
    executor:
      name: node/default
    steps:
      - checkout
      - run:
        working_directory: server
        npm install
        npm test


workflows:
    build-and-test:
      jobs:
        - klient
        - serwer